### ISSUE TITLE
Is there any plan to bind packmol with python?

### ISSUE THREAD

**Issue by Roy-Kid** [m3g/packmol#52]
Hi, I want to ask is there any plan to bind packmol with python. It will be very useful in the workflow~

**Comment by lmiq** [comment]
No, not really. Bind in what sense? There are quite a few python packages that call packmol already.

**Comment by Roy-Kid** [comment]
My point is, I can directly pass molecules' position in numpy to packmol and get the optimized data back. So i can avoid to convert the model to pdb format. 

I am trying to bind it with f2py. I want to bind those methods in `src` and invoke them by rewriting `packmol.f90` in python. But I'm having some [difficulty](https://matrix.to/#/!rvchEJoxPoOJsQNTMg:gitter.im/$3ZOzhvKJgiOrKQgataLukR0FQeHCWPquI-P1gxy619E?via=gitter.im&via=mozilla.org&via=matrix.org), maybe `jacobi.f90` is written with the syntax of f77? I am not sure as well

By the way, which package have wrapped the packmol. I have searched it in github and found no one.

**Comment by lmiq** [comment]
I'm not a python user, so I cannot tell how useful are these packages, but from googling a bit I found:

https://pypi.org/project/packmol-step/

https://github.com/MDAnalysis/MDAPackmol

https://github.com/virtualzx-nad/pypackmol

The `gencan.f` source is a fortran77-style file. The jacobi.f90 is a literal translation of an old routine to Fortran90 but yes, it is pretty old.

I'm not sure how hard is to wrap packmol to be called directly using numpy arrays, I guess that's not very easy, because there are quite a few auxiliary arrays that need to be allocated to make packmol work, and the package is not structured in a very modular fashion.

That said, currently I am developing a new version of Packmol in Julia (https:://github.com/m3g/Packmol.jl) which will be more modular and easy to interface with numpy as you suggest (it will be also faster, parallel, and more flexible).

**Comment by lmiq** [comment]
In summary: I don't have any plan to bind packmol with python, at least not this version of Packmol. But if you are willing to work on that, I'm happy to help if possible.

**Comment by PythonFZ** [comment]
I have included build wheels for Mac / Windows / Linux by adding packmol as a submodule to https://github.com/zincware/molify and using https://cibuildwheel.pypa.io/en/stable/ for distribution.

According to the packmol licence this should not be an issue and I will add more information about correct citation to the package soon.

@lmiq you made it quite clear, that you are not interested in providing a python installation for packmol yourself, but e.g. the very python focused machine-learned interatomic potential community would benefit from including packmol natively into their workflows without the (small) extra step of compilation. If you are interested, I could provide a PR that can release packmol to pypi on release actions? E.g. https://pypi.org/project/packmol/ should still be available.

**Comment by lmiq** [comment]
I have no objections to that, although I don't know exactly what it means. Packmol is available through conda already, I don't know if that's enough.
